- name: December & Company
  image: dco.jpeg
  url: https://dco.com
  oneliner: Platform for algorithmic trading
  role: Developer
  description: >
    As a member of software engineers of December & Company, I developed new platform for algorithmic trading.
    Main targets are stocks, futures and supporting mathematical strategies.
  technologies:
    - Python(Flask)
    - C++
    - PostgreSQL
    - Javascript





